### ISSUE TITLE
gradle run does not work

### ISSUE THREAD

**Issue by mingan666** [ev3dev-lang-java/gradle-plugin#2]
I'm not able to run the template project through the gradle command. For some reason the -Xshare:on does not work for my setup.

So I tried to run it locally on the pi with the following java commands. The second try I removed the -Xshare:on and it worked fine.

```
robot@ev3dev:~$ java -Xms64m -Xmx64m -XX:+UseSerialGC -Xshare:on -noverify -jar "/home/robot/java/programs/template_project_gradle-2.5.3.jar"
An error has occurred while processing the shared archive file.
Specified shared archive not found.
Error occurred during initialization of VM
Unable to use shared archive.
robot@ev3dev:~$
robot@ev3dev:~$ java -Xms64m -Xmx64m -XX:+UseSerialGC -noverify -jar "/home/robot/java/programs/template_project_gradle-
2.5.3.jar"
Hello World
```

Any ideas?

**Comment by JakubVanek** [comment]
Hackability note: java flags can be overriden by adding this somewhere in the project which uses this plugin:
```gradle
brick.pref {
  jvmFlags = ["-Xms64m", "-Xmx64m", "-XX:+UseSerialGC", "-noverify"] // without -Xshare:on
}
```
This overrides the default definition from [here](https://github.com/ev3dev-lang-java/gradle-plugin/blob/ec25ab3daa57a09a7370e8d6926a5ff3b858d87d/src/main/groovy/com/github/elj/gradle/Preferences.groovy#L19).

**Comment by mingan666** [comment]
Thanks for the info. I've been googling a bit and finally found some explanations about what the flag is used for. Why did you add the flag? Is it due to the slow startup of java on the EV3?

The suggestion above worked fine, however I'm not sure if it is really beneficial on the pi to run with that flag.

As described [here](https://docs.oracle.com/javase/8/docs/technotes/guides/vm/class-data-sharing.html) it is not that uncommon. So I think it might be good to add the `sudo java -Xshare:dump` to the install, since others using pi might also run into this problem. Then the plugin gradle jobs should hopefully work out of the box for pi also.

**Comment by mingan666** [comment]
Yes, I did some digging in the plugin code and found the different configurations. This plugin works nice and it seems easy to personalize. Good work!
