### ISSUE TITLE
Feature request: install java libs from project dependencies

### ISSUE THREAD

**Issue by viniciusccarvalho** [ev3dev-lang-java/gradle-plugin#4]
Hi there, first thank you for this amazing project, being a lejos user for a while, it's so nice to see a new refresh on java on ev3 :)

I usually build my bots with kotlin, so I have a couple of extra jars on my classpath. Instead of creating a fatJar I usually just move them to a folder where I can load using `Class-Path`. 

It would be really nice if the gradle task that install the java libraries on the brick could collect the project libraries too, or perhaps a new task.

**Comment by JakubVanek** [comment]
Hi @viniciusccarvalho,

this feature has been already implemented, though it is not documented. The examples project makes use of it: https://github.com/ev3dev-lang-java/examples

```sh
./gradlew uploadGradleLibraries
./gradlew deploy
```

Regards,

Jakub

**Comment by viniciusccarvalho** [comment]
Hi @JakubVanek thank you for pointing this out. One note to add, if you use `implementation` (which is the new recommended way) and not `compile` on gradle, the libraries are not picked.

Cheers

**Comment by JakubVanek** [comment]
Hi,

oki, this seems interesting. I used the indeed deprecated `runtime` configuration [here][1] to collect the dependencies. However it seems that switching to [`runtimeClasspath`][2] might solve the problem. I will look at it tomorrow.

Thanks,

Jakub

[1]: https://github.com/ev3dev-lang-java/gradle-plugin/blob/b996e72573e21a3f362b4a163b48c602bdaeee3e/src/main/groovy/com/github/elj/gradle/GradlePlugin.groovy#L96
[2]: https://docs.gradle.org/current/userguide/java_plugin.html#tab:configurations

**Comment by JakubVanek** [comment]
This is mostly fixed and I plan to create an issue for automatic deployment for dependencies, so I'm closing this issue.
